Specify encoding of README to avoid UnicodeDecodeError
This error was seen with Python 3.4 on Linux when LANG wasn't set:

Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    long_description=convert('README.md', 'rst'),
  File "setup.py", line 12, in convert
    return fd.read()
  File "/home/trawick/.virtualenvs/2015-12-17-2/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 876: ordinal not in range(128)

580ab67@jrief added non-ASCII characters to the README, which then
required that the encoding be properly guessed.